### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by FabricioGastino** [ShoobyDoo/OPGG.py#43]
Hi, I would like to know if with your code it is possible for me to create a command like !playing, which returns whether or not the account in question is currently playing. thanks for making it available

**Comment by ShoobyDoo** [comment]
Hi,

Currently there isn't such functionality, however I believe this should be pretty simple to implement. I am currently working on a major rewrite of the library so keep your eye out for the full 2.0 release which should include this feature as well.

**Comment by FabricioGastino** [comment]
ok. thanks for reply
